### ISSUE TITLE
How can I fix the outline that gets thicker when the FOV is low?

### ISSUE THREAD

**Issue by TofuFromSekai** [Elysia-simp/Shitkai-Shader#4]
![test](https://github.com/Elysia-simp/Shitkai-Shader/assets/152696173/a1ec8ca9-cb47-4ea2-99d8-e0f7842f8f6f)

I'm using your shader well. But when the FOV is low, the outline gets thicker. Do you know how to fix this? If it's impossible, I'll just use it.

**Comment by Elysia-simp** [comment]
Fixed in 1.1b
