### ISSUE TITLE
SHADOW_COL affects the entire skin color

### ISSUE THREAD

**Issue by anonRipper** [Elysia-simp/Shitkai-Shader#7]
I noticed that changing SHADOW_COL value affects the entire skin color. So I tried to fix it by changing the beginning of Shitkai_Coloring function like this. Is this change correct?
```
    float3 DefaultSkinColor = skinColorTable[u_xlati9];
    #ifdef _DefaultSkinColor
    DefaultSkinColor = _DefaultSkinColor;
    #endif

    float3 Shadow1SkinColor = skinShadow1Table[u_xlati9];
    #ifdef Shadow1SkinColor
    Shadow1SkinColor = _Shadow1SkinColor;
    #endif
	Shadow1SkinColor -= S;

    float3 Shadow2SkinColor = skinShadow2Table[u_xlati9];
    #ifdef Shadow1SkinColor
    Shadow2SkinColor = _Shadow1SkinColor;
    #endif
	Shadow2SkinColor -= S;

    float3 u_xlat16_6;
    float3 u_xlat4 = _SekaiShadowColor.xyz * Shadow1SkinColor.xyz;
    float3 u_xlat5 = _SekaiShadowColor.xyz * Shadow1SkinColor.xyz;
```
![before](https://github.com/user-attachments/assets/1bc05777-c6a7-4467-bb53-e3443ef2340c)

**Comment by Elysia-simp** [comment]
Skin coloring only works as intended for models that need skin coloring (their skin is completely white) would not work as intended otherwise. As your code is edited, I can only assume you removed the logic that prevented this from happening. As I cannot replicate it on my end.
